### ISSUE TITLE
CPU extensions break multitasking

### ISSUE THREAD

**Issue by deboogerxyz** [fs-os/fs-os#10]
XMM registers aren't saved when context switching.

**Comment by deboogerxyz** [comment]
Disabling SSE2 fixes random screen flashes with optimization level >2.

**Comment by deboogerxyz** [comment]
> XMM registers aren't saved when context switching.

https://wiki.osdev.org/SSE#FXSAVE_and_FXRSTOR

**Comment by 8dcc** [comment]
Fixed in #13
